### ISSUE TITLE
[Android] [KitKat] java.lang.NullPointerException

### ISSUE THREAD

**Issue by Xwalk-Company** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#142]
Hi,
I have an error (sending by google from user) on my dashboard in Play Google.

The report:
![crashcamerapreview](https://cloud.githubusercontent.com/assets/9979292/20534770/bbe11e46-b0e2-11e6-9343-cb8dc5fd0735.PNG)

I can't find the problem...
The device is Xperia M2 (D2303)

I think the problem lies in the selection of the camera with its identifier, but I can not understand what is problem (no error elsewhere)

**Comment by erperejildo** [comment]
Can you try with latest version (from Github, not npm)

**Comment by cometta** [comment]
I still experience this error with version from github

> java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
  at android.app.ActivityThread.access$800(ActivityThread.java:147)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5237)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Caused by: java.lang.NullPointerException: 
  at com.cordovaplugincamerapreview.CameraActivity.setDefaultCameraId(CameraActivity.java:225)
  at com.cordovaplugincamerapreview.CameraActivity.createCameraPreview(CameraActivity.java:110)
  at com.cordovaplugincamerapreview.CameraActivity.onCreateView(CameraActivity.java:97)
  at android.app.Fragment.performCreateView(Fragment.java:2053)
  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
  at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1871)
  at android.app.Activity.performCreateCommon(Activity.java:5977)
  at android.app.Activity.performCreate(Activity.java:5984)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)

**Comment by HartHerbert** [comment]
me too but not only with the kitkat android version, also with nougat (7.0)

**Comment by maxborgatti** [comment]
Any update on that?

**Comment by itsonit** [comment]
same for Samsung Galaxy Note8 on current master

**Comment by DualH** [comment]
Any update on that?

**Comment by DualH** [comment]
I got the same
```java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2957)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: 
  at com.cordovaplugincamerapreview.CameraActivity.setDefaultCameraId (CameraActivity.java:250)
  at com.cordovaplugincamerapreview.CameraActivity.createCameraPreview (CameraActivity.java:115)
  at com.cordovaplugincamerapreview.CameraActivity.onCreateView (CameraActivity.java:102)
  at android.app.Fragment.performCreateView (Fragment.java:2611)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1276)
  at android.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1549)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1611)
  at android.app.FragmentManagerImpl.dispatchMoveToState (FragmentManager.java:3045)
  at android.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManager.java:2997)
  at android.app.FragmentController.dispatchActivityCreated (FragmentController.java:179)
  at android.app.Activity.performCreateCommon (Activity.java:7177)
  at android.app.Activity.performCreate (Activity.java:7185)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1220)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2910)```
