### ISSUE TITLE
App Crash with Google Maps turned On

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#290]
We are using this plugin along with: Cordova Google Maps https://github.com/mapsplugin/cordova-plugin-googlemaps the app crash everytime we start the camera.

**Comment by battika** [comment]
Hello,

I have the same issue upon camera start.

Here is the logcat output of what happens:

```
05-01 19:35:04.345 18738 18833 W PluginManager: THREAD WARNING: exec() call to CameraPreview.startCamera blocked the main thread for 34ms. Plugin should use CordovaInterface.getThreadPool().

05-01 19:35:04.355 18738 18738 E UncaughtException:
05-01 19:35:04.355 18738 18738 E UncaughtException: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
05-01 19:35:04.355 18738 18738 E UncaughtException:     at com.cordovaplugincamerapreview.CameraPreview$1.run(CameraPreview.java:232)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at android.os.Handler.handleCallback(Handler.java:743)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at android.os.Looper.loop(Looper.java:150)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at android.app.ActivityThread.main(ActivityThread.java:5665)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at java.lang.reflect.Method.invoke(Native Method)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
05-01 19:35:04.355 18738 18738 E UncaughtException:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```

**Comment by edu526** [comment]
If they still do not fix it, you can use the remove() method of Google Map before entering the camera page

**Comment by THEDOWNCOUNTRY** [comment]
Are you using Google maps with this plugin?

**Comment by cburyta** [comment]
I'm also having this issue, (I believe even when using the 'master' branch with the patch for #340 )

I'm using the cordova-plugin-camera-preview plugin with the https://github.com/mapsplugin/cordova-plugin-googlemaps. I've tried with that plugin's master branch and with the '2.1.1' release.

(I can try and provide an example app if it helps.)
