### ISSUE TITLE
camera preview failed to start

### ISSUE THREAD

**Issue by immnk** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#368]
I am having a weird problem now. I am running an ionic app using native google map plugin and camera preview plugin. I have a google map native plugin installed and use google map. When I launch the camera preview page after opening google map, the app crashes with the stack trace:

```
09-27 12:34:04.165 15251-15251/com.hvhc.memberapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.hvhc.memberapp, PID: 15251
                                                                    java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
                                                                        at com.cordovaplugincamerapreview.CameraPreview$1.run(CameraPreview.java:241)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:157)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                        at dalvik.system.NativeStart.main(Native Method)
```

Also there is this problem when the requesting permission:

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:reques
tPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com
.packagename.appname/com.packagename.appname.MainActivity}: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android
.widget.FrameLayout
```

**Comment by HartHerbert** [comment]
same

**Comment by HartHerbert** [comment]
did you solve this issue @immnk ?

**Comment by HartHerbert** [comment]
pull request to solve this issue #399

**Comment by HartHerbert** [comment]
@immnk check if it is working now for you and then close this issue
