### ISSUE TITLE
stopCamera() crashes app in current master

### ISSUE THREAD

**Issue by Farbdose** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#401]
**Note: this is working fine in the 0.9.0 release**

I'm trying to stop the preview after I'm finished ... which results in a crash.

I'm using `@ionic-native/camera-preview@4.5.2` and the current master (3389a9c0a979005294fc1039b31141a9c6dd78b4)

I can successfully start the preview with:

```
startCamera() {
	console.log("Starting camera...");
	let cameraPreviewOpts = {
		x: 0,
		y: 0,
		width: window.screen.width,
		height: window.screen.height,
		camera: "rear",
		toBack: true,
		tapPhoto: false,
		tapFocus: false,
		previewDrag: false
	};
	this.cameraPreview.startCamera(cameraPreviewOpts).then(
		(res) => {
			console.log(res);
		},
		(err) => {
			console.log(err);
		});
}
```
But as soon as I call stopCamera():
```
ngOnDestroy() {
	this.cameraPreview.stopCamera().then(
		(res) => {
			console.log(res);
		},
		(err) => {
			console.log(err);
		});
}
```

The app chrashes with:
```
12-14 13:16:04.664: E/Preview(15804): Exception caused by surfaceDestroyed()
12-14 13:16:04.664: E/Preview(15804): java.lang.RuntimeException: Camera is being used after Camera.release() was called
12-14 13:16:04.664: E/Preview(15804): 	at android.hardware.Camera._stopPreview(Native Method)
12-14 13:16:04.664: E/Preview(15804): 	at android.hardware.Camera.stopPreview(Camera.java:753)
12-14 13:16:04.664: E/Preview(15804): 	at com.cordovaplugincamerapreview.Preview.surfaceDestroyed(Preview.java:233)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:581)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:243)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.View.dispatchDetachedFromWindow(View.java:14644)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4604)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4577)
12-14 13:16:04.664: E/Preview(15804): 	at android.view.ViewGroup.removeView(ViewGroup.java:4508)
12-14 13:16:04.664: E/Preview(15804): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1068)
12-14 13:16:04.664: E/Preview(15804): 	at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1253)
12-14 13:16:04.664: E/Preview(15804): 	at android.app.BackStackRecord.run(BackStackRecord.java:758)
12-14 13:16:04.664: E/Preview(15804): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
12-14 13:16:04.664: E/Preview(15804): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
12-14 13:16:04.664: E/Preview(15804): 	at android.os.Handler.handleCallback(Handler.java:739)
12-14 13:16:04.664: E/Preview(15804): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-14 13:16:04.664: E/Preview(15804): 	at android.os.Looper.loop(Looper.java:234)
12-14 13:16:04.664: E/Preview(15804): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
12-14 13:16:04.664: E/Preview(15804): 	at java.lang.reflect.Method.invoke(Native Method)
12-14 13:16:04.664: E/Preview(15804): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-14 13:16:04.664: E/Preview(15804): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Followed by:
```
12-14 13:16:04.673: E/AndroidRuntime(15804): FATAL EXCEPTION: main
12-14 13:16:04.673: E/AndroidRuntime(15804): Process: com.************************, PID: 15804
12-14 13:16:04.673: E/AndroidRuntime(15804): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View, int)' on a null object reference
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at com.cordovaplugincamerapreview.CameraPreview$2.run(CameraPreview.java:786)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at android.os.Handler.handleCallback(Handler.java:739)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at android.os.Looper.loop(Looper.java:234)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at java.lang.reflect.Method.invoke(Native Method)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-14 13:16:04.673: E/AndroidRuntime(15804): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Please inform me which information you need to debug this issue...** as I would like to use the latest version and not the 0.9.0 release...

**Comment by Choppel** [comment]
@Farbdose 
1.) Try to find out if the app crashes on the first or one of the other stopCamera calls. If it's never the first then you should call stopCamera only if the camera is started.

2.) That's the problem with dev releases. You can never be sure it they work the way they should.
Even if you could get the current master to work. You wouldn't know if the master that's released in e.g. 15 days is working the way you want it to.

**Comment by Farbdose** [comment]
Ok, I will report back when my project server comes back online next week ...

**Comment by tylerpashigian** [comment]
Is this still happening to anyone else? I am still having this issue on iOS. I am getting the following error in my logs: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'. The app goes to main.m in the main() function when it crashes.

**Comment by kwangpatta** [comment]
> Is this still happening to anyone else? I am still having this issue on iOS. I am getting the following error in my logs: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'. The app goes to main.m in the main() function when it crashes.

Yes, It's still happened to me.
