### ISSUE TITLE
startCamera is not a function

### ISSUE THREAD

**Issue by sdhnt** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#547]
Hey, I'm trying to get get the following code to work:

`let options = {
      x: 0,
      y: 0,
      width: window.screen.width,
      height: window.screen.height,
      camera: 'rear',
      toBack: false,
      tapPhoto: true,
      tapFocus: false,
      previewDrag: false,
      storeToFile: false,
      disableExifHeaderStripping: false
    };
    
    this.cameraPreview.startCamera(options);`

However, I'm constantly getting this error:

`Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at CameraPreview.startCamera (http://localhost:8100/build/vendor.js:73129:138)
    at ReceiverPage.webpackJsonp.78.ReceiverPage.cameraBackground (http://localhost:8100/build/main.js:1394:28)
    at new ReceiverPage (http://localhost:8100/build/main.js:1378:14)
    at createClass (http://localhost:8100/build/vendor.js:12865:20)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:12700:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:14158:53)
    at createRootView (http://localhost:8100/build/vendor.js:14047:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:14755:12)
    at ComponentFactory_.create (http://localhost:8100/build/vendor.js:11652:46)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:52541:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:52534:14)
    at http://localhost:8100/build/vendor.js:52581:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5134:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242`

Here's my package.json:

`{
  "name": "todo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/camera": "^4.20.0",
    "@ionic-native/camera-preview": "^5.7.0",
    "@ionic-native/core": "~4.17.0",
    "@ionic-native/device-orientation": "^4.20.0",
    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/image-picker": "^4.20.0",
    "@ionic-native/screen-orientation": "^4.20.0",
    "@ionic-native/splash-screen": "~4.17.0",
    "@ionic-native/status-bar": "~4.17.0",
    "@ionic/storage": "2.2.0",
    "cordova-android": "7.1.4",
    "cordova-plugin-camera": "4.0.3",
    "cordova-plugin-camera-preview": "git+https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-device-orientation": "^2.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.3",
    "cordova-plugin-screen-orientation": "3.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-telerik-imagepicker": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cors": "^2.8.5",
    "delay": "^4.2.0",
    "es6-promise-plugin": "4.2.2",
    "firebase": "^5.7.0",
    "geolib": "^2.0.24",
    "ionic": "^4.9.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "moment": "^2.22.2",
    "ng-simple-slideshow": "^1.2.8",
    "resonance-audio": "^1.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.4",
    "@ionic/lab": "1.0.15",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-telerik-imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "Accessing Gallery"
      },
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-device-orientation": {},
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-camera-preview": {}
    },
    "platforms": [
      "android"
    ]
  }
}`

**Comment by xuanphu123** [comment]
@sdhnt change @ionic-native/camera-preview to v4
