### ISSUE TITLE
Front Camera Video Record - App Crash

### ISSUE THREAD

**Issue by AAnish11** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#623]
Hello ,

When i am trying to record the video from front camera , i am getting below error
```
E/MediaRecorder: start failed: -19
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
                  Process: com.hot_rod.com, PID: 17944
                  java.lang.RuntimeException: start failed.
                      at android.media.MediaRecorder.start(Native Method)
                      at com.cordovaplugincamerapreview.CameraActivity.startRecord(CameraActivity.java:738)
                      at com.cordovaplugincamerapreview.CameraPreview$2.run(CameraPreview.java:439)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                      at java.lang.Thread.run(Thread.java:764)
W/com.hot_rod.com: type=1400 audit(0.0:15658): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=13750 scontext=u:r:untrusted_app:s0:c24,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/CordovaActivity: Paused the activity.
I/Process: Sending signal. PID: 17944 SIG: 9
```

Can anyone help me on this.

**Comment by rajubera** [comment]
Hello @westonganger  just wondering why it's closed. Do we already have a solution to it? I am also facing this issue integrating opentok plugin in a ionic app
